### ISSUE TITLE
Props should be there to change the color of the disabled toggle button color

### ISSUE THREAD

**Issue by asgupta9** [ashishpandey001/react-native-flip-toggle-button#15]

**Comment by ashishpandey001** [comment]
Okay, thank you for the suggestion, will provide a new release by tonight with that functionality.

**Comment by ashishpandey001** [comment]
Fixed in [5d9e087](https://github.com/ashishpandey001/react-native-flip-toggle-button/commit/5d9e0879b8487d4ac0932fbc3d8cc56a29d51d7f)
