### ISSUE TITLE
onLabel Not Displaying

### ISSUE THREAD

**Issue by dl-husky73** [ashishpandey001/react-native-flip-toggle-button#20]
I am not sure what is happening but I am trying to use this package and the onLabel property is not displaying.  Pretty simple use case with RN-62. 

                                <FlipToggle
                                    value={switch1}
                                    buttonWidth={90}
                                    buttonHeight={36}
                                    buttonRadius={50}
                                    sliderWidth={35}
                                    sliderHeight={36}
                                    sliderRadius={50}
                                    onLabel={'on'}
                                    offLabel={'off'}
                                    labelStyle={{ color: 'white' }}
                                    sliderOnColor="green"
                                    sliderOffColor="red"
                                    buttonOffColor="blue"
                                    buttonOnColor="blue"
                                    onToggle={g_switch1}
                                />

**Comment by ashishpandey001** [comment]
Here's a [sample](https://snack.expo.io/@hmaster0/rn-flip-toggle-onlabel-issue) which shows that this works without issues.
Closing this issue.
